language: erlang
branches:
        only:
                - master
notifications:
        email: lvzecai@gmail.com

otp_release:
        - 17.1
        - 17.0
        - R16B03
        - R15B03

before_script:
        - make extra-deps
        - make mongooseim-start

script:
        - make
        - make test
        - make ct

after_script:
        - make mongooseim-stop
